---
version: 0.2
env:
  parameter-store:
    MONDOO_CONFIG_BASE64: "MONDOO_CONFIG_BASE64"
    

phases:
  pre_build:
    commands:
      - echo "Installing HashiCorp Terraform..."
      - curl -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip && unzip terraform.zip
      - echo "Installing cnspec..."
      - curl -qL -o cnspec.tar.gz https://releases.mondoo.com/cnspec/7.5.1/cnspec_7.5.1_linux_amd64.tar.gz && tar xzvf cnspec.tar.gz
      - echo "Checking status with Mondoo Platform"
      - cnspec status
  build:
    commands:
      ### HashiCorp Packer cannot currently obtain the AWS CodeBuild-assigned role and its credentials
      ### Manually capture and configure the AWS CLI to provide HashiCorp Packer with AWS credentials
      ### More info here: https://github.com/mitchellh/packer/issues/4279
      - echo "Configuring AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - echo "Building HashiCorp Packer template, amazon_linux_packer_template.json"
      - ./packer build amazon_linux_packer_template.json
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"